---
- name: Install Epel
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start Nginx
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Install Git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Download Lighthouse
  become: true
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /usr/share/nginx/lighthouse
    version: d701335
    force: true
- name: Prepare Lighthouse static to serve via nginx
  become: true
  ansible.builtin.file:
    path: /usr/share/nginx/lighthouse
    mode: '0755'
    recurse: true
- name: Configure Nginx
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: '0755'
  notify: Reload Nginx
