---
- name: Start Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
- name: Reload Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
